[package]
name = "svg_exploit_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
tokio = { version = "1.39.2", features = ["full"] }
quick-xml = "0.36.1"
thiserror = "1.0.63"
